issuer: "https://{{ .Env.DEX_DOMAIN }}/dex"
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
web:
  http: "0.0.0.0:5556"
frontend:
  issuer: "/dex"
  theme: "dark"
telemetry:
  http: "0.0.0.0:5558"
oauth2:
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
staticClients:
  - name: "Grist"
    id: "grist"
    secret: "{{ .Env.GRIST_OAUTH_CLIENT_SECRET }}"
    redirectURIs: ["https://{{ .Env.GRIST_DOMAIN }}/oauth2/callback"]
enablePasswordDB: true
staticPasswords:
  - username: "admin"
    email: "admin@example.localhost"
    hash: "{{ .Env.DEX_DEMO_USERS_PASSWORD_HASH }}"
  - username: "alice"
    email: "alice@example.localhost"
    hash: "{{ .Env.DEX_DEMO_USERS_PASSWORD_HASH }}"
  - username: "bob"
    email: "bob@example.localhost"
    hash: "{{ .Env.DEX_DEMO_USERS_PASSWORD_HASH }}"
